# Cosmos Discord Faucet configuration

verbose        = "yes"

[cosmos]
prefix         = "hid"
denomination   = "uhid"

[testnets]
    [testnets.devnet]
    node_url = "tcp://0.0.0.0:26657"
    chain_id = "jagrat"
    faucet_address = "hid1c0qs3eyu5pqqwr70j2klsrpuqhjd8xqqeuj22x"
    block_explorer_tx = "https://explorer.hypersign.id/hypersign-devnet/tx/"
    daily_cap = "400000000"
    amount_to_send = "10000000"
    tx_fees = "4000"

[discord]
bot_token = ""
# comma separated list of channels
channels_to_listen = "devnet-faucet"
# how often user can request tokens from faucet (seconds)
# 10800 = 3  hours
# 86400 = 24 hours
request_timeout    = "86400"